// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2Gm84QXKMfEgoNmE0ju4_4036ltTwO4',
    appId: '1:533854786827:web:7e45d49bdbbe8c2ce43e0e',
    messagingSenderId: '533854786827',
    projectId: 'prj-p-k9canine-ip-a344',
    authDomain: 'prj-p-k9canine-ip-a344.firebaseapp.com',
    storageBucket: 'prj-p-k9canine-ip-a344.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW9jJwaPZwTtGdoCxASZz9CGFqkzQ1lXs',
    appId: '1:533854786827:android:063c7b7240fad493e43e0e',
    messagingSenderId: '533854786827',
    projectId: 'prj-p-k9canine-ip-a344',
    storageBucket: 'prj-p-k9canine-ip-a344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztWs1di03PKlejGop2AbQyLfBVd9tJ_k',
    appId: '1:533854786827:ios:c28bc58a559e33cee43e0e',
    messagingSenderId: '533854786827',
    projectId: 'prj-p-k9canine-ip-a344',
    storageBucket: 'prj-p-k9canine-ip-a344.appspot.com',
    iosBundleId: 'fr.bjrdoc.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAztWs1di03PKlejGop2AbQyLfBVd9tJ_k',
    appId: '1:533854786827:ios:e7151dd965c53c09e43e0e',
    messagingSenderId: '533854786827',
    projectId: 'prj-p-k9canine-ip-a344',
    storageBucket: 'prj-p-k9canine-ip-a344.appspot.com',
    iosBundleId: 'fr.clemia.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk2Gm84QXKMfEgoNmE0ju4_4036ltTwO4',
    appId: '1:533854786827:web:15ef2f12300115d8e43e0e',
    messagingSenderId: '533854786827',
    projectId: 'prj-p-k9canine-ip-a344',
    authDomain: 'prj-p-k9canine-ip-a344.firebaseapp.com',
    storageBucket: 'prj-p-k9canine-ip-a344.appspot.com',
  );

}