//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Conversations = newConversationsTable("public", "conversations", "")

type conversationsTable struct {
	postgres.Table

	// Columns
	ID            postgres.ColumnInteger
	User1ID       postgres.ColumnInteger
	User2ID       postgres.ColumnInteger
	CreatedAt     postgres.ColumnTimestamp
	LastMessageID postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ConversationsTable struct {
	conversationsTable

	EXCLUDED conversationsTable
}

// AS creates new ConversationsTable with assigned alias
func (a ConversationsTable) AS(alias string) *ConversationsTable {
	return newConversationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ConversationsTable with assigned schema name
func (a ConversationsTable) FromSchema(schemaName string) *ConversationsTable {
	return newConversationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ConversationsTable with assigned table prefix
func (a ConversationsTable) WithPrefix(prefix string) *ConversationsTable {
	return newConversationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ConversationsTable with assigned table suffix
func (a ConversationsTable) WithSuffix(suffix string) *ConversationsTable {
	return newConversationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newConversationsTable(schemaName, tableName, alias string) *ConversationsTable {
	return &ConversationsTable{
		conversationsTable: newConversationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newConversationsTableImpl("", "excluded", ""),
	}
}

func newConversationsTableImpl(schemaName, tableName, alias string) conversationsTable {
	var (
		IDColumn            = postgres.IntegerColumn("id")
		User1IDColumn       = postgres.IntegerColumn("user1_id")
		User2IDColumn       = postgres.IntegerColumn("user2_id")
		CreatedAtColumn     = postgres.TimestampColumn("created_at")
		LastMessageIDColumn = postgres.IntegerColumn("last_message_id")
		allColumns          = postgres.ColumnList{IDColumn, User1IDColumn, User2IDColumn, CreatedAtColumn, LastMessageIDColumn}
		mutableColumns      = postgres.ColumnList{User1IDColumn, User2IDColumn, CreatedAtColumn, LastMessageIDColumn}
	)

	return conversationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:            IDColumn,
		User1ID:       User1IDColumn,
		User2ID:       User2IDColumn,
		CreatedAt:     CreatedAtColumn,
		LastMessageID: LastMessageIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
