apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: canine-gke-app-p-sa@prj-p-k9canine-base-f4s4.iam.gserviceaccount.com
  labels:
    env: prod
  name: canine-app
  namespace: default
---
apiVersion: v1
data:
  AUTH_REALM: p
  AUTH_SECRET_SM_NAME: projects/prj-p-k9env-kms-zyow/secrets/jwt_secret/versions/2
  GIN_MODE: release
  INSTANCE_CONNECTION_NAME: prj-p-k9canine-sql-y3aq:europe-west9:canine-sql-1-p-europe-west9-2b17793a
  LOG_LEVEL: debug
  POSTGRES_DSN: postgres://canine-gke-app-p-sa%40prj-p-k9canine-base-f4s4.iam:not-a-password@localhost:5432/canine
kind: ConfigMap
metadata:
  labels:
    env: prod
  name: canine-app-config-dkt2hm9bgc
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "canine-ingress-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    env: prod
  name: canine-app
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: canine-app
    env: prod
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canine-app
    env: prod
  name: canine-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canine-app
      env: prod
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: canine-app
        env: prod
      name: app
    spec:
      containers:
        - args:
            - api
          env:
            - name: ENVIRONMENT
              value: prod
            - name: AUTH_SECRET_SM_NAME
              valueFrom:
                configMapKeyRef:
                  key: AUTH_SECRET_SM_NAME
                  name: canine-app-config-dkt2hm9bgc
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: canine-app-config-dkt2hm9bgc
            - name: POSTGRES_DSN
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DSN
                  name: canine-app-config-dkt2hm9bgc
            - name: AUTH_REALM
              valueFrom:
                configMapKeyRef:
                  key: AUTH_REALM
                  name: canine-app-config-dkt2hm9bgc
            - name: INSTANCE_CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  key: INSTANCE_CONNECTION_NAME
                  name: canine-app-config-dkt2hm9bgc
            - name: GIN_MODE
              valueFrom:
                configMapKeyRef:
                  key: GIN_MODE
                  name: canine-app-config-dkt2hm9bgc
          image: europe-west9-docker.pkg.dev/prj-c-k9app-cicd-rv1i/prj-c-k9app-cicd-rv1i-app-k9-image-repo/image-canine-20240507105627/app:4906c0b-dirty@sha256:ecebbea60ec50a8bd83902ceb36812a7a09896780e5794771910c411d7589292
          name: app
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
          resources:
            limits:
              cpu: 20m
              memory: 200Mi
      serviceAccountName: canine-app
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  labels:
    env: prod
  name: canine-ingress-backendconfig
  namespace: default
spec:
  healthCheck:
    port: 8080
    requestPath: /healthz
    type: HTTP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: ingress-ip
  labels:
    env: prod
  name: canine-ingress
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: canine-app
                port:
                  number: 80
            path: /api/v1/*
            pathType: ImplementationSpecific
