run:
  timeout: 5m
  skip-dirs:
    - .gen

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - goheader
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
  disable:
    - cyclop # TODO(complexity): enable
    - funlen # TODO(complexity): enable
    - gci # formatting is checked by CI
    - gocognit # TODO(complexity): enable
    - goconst # i'm not sure we want to enable, a bit annoying
    - godox # we don't need to warn about todos
    - gofmt # formatting is checked by CI
    - gofumpt # formatting is checked by CI
    - goimports # formatting is checked by CI
    - nestif # TODO(complexity): enable
    - wsl # we don't want to enforce empty lines

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  varnamelen:
    ignore-names:
      - ok