run:
  timeout: 5m
  skip-dirs:
    - .gen

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - goheader
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
#    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
  disable:
    - cyclop # TODO(complexity): enable
    - funlen # TODO(complexity): enable
    - gci # formatting is checked by CI
    - gocognit # TODO(complexity): enable
    - goconst # i'm not sure we want to enable, a bit annoying
    - godox # we don't need to warn about todos
    - gofmt # formatting is checked by CI
    - gofumpt # formatting is checked by CI
    - goimports # formatting is checked by CI
    - nestif # TODO(complexity): enable
    - wsl # we don't want to enforce empty lines

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  varnamelen:
    ignore-names:
      - ok
  revive:
    rules:
      - name: dot-imports
        disabled: true # FIXME: enable when it is going to handle allowed packages
        arguments:
          - allowedPackages:
            - "github.com/onsi/ginkgo/v2"
            - "github.com/onsi/gomega"
  tagliatelle:
    # Check the struck tag name case.
    case:
      # Use the struct field name to check the name of the struct tag.
      use-field-name: true
      rules:
        json: snake
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - 'back'
          - 'github.com/spf13/pflag' # clearly unmaintained, but we need it
          - 'github.com/rs/zerolog'
          - 'github.com/gin-gonic/gin'
          - 'github.com/appleboy/gin-jwt/v2'
          - 'firebase.google.com/go/v4/auth'
          - 'github.com/zitadel/oidc'
          - 'github.com/zitadel/zitadel-go/v2'
          - 'github.com/jackc/pgerrcode'
          - 'github.com/jackc/pgx'
          - 'github.com/go-jet'
          - "cloud.google.com/go/pubsub"
          - "github.com/sendgrid/sendgrid-go"
          - "cloud.google.com/go/storage"
          - "github.com/twilio/twilio-go"
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - "StateMachine"
      - back\/internal\/pkg\/domain\/.*
issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - goerr113
