# build and run chat
version: '3'
services:
  api:
    build:
      dockerfile: build/Dockerfile
      context: .
    ports:
      - "8080:8080"
    command: ["api"]
    depends_on:
      db:
        condition: service_healthy
    environment:
        DSN: "postgres://postgres:postgres@db:5432/canine?sslmode=disable"

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: canine

volumes:
    pg-data:
