# build and run chat
version: '3'
services:
#  api:
#    build:
#      dockerfile: build/Dockerfile
#      context: .
#    ports:
#      - "8080:8080"
#    command: ["api"]
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#        DSN: "postgres://postgres:postgres@db:5432/canine?sslmode=disable"

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: canine
  rdb:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  gcs-emulator:
    build:
      target: gcsemulator
      context: https://github.com/adriantofan/emulators.git
      args:
        VERSION: 1.0.0
    ports:
      - "9000:9000"
    volumes:
      - gcs-data:/data


volumes:
    pg-data:
    redis-data:
    gcs-data:

