name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  web_socket_channel: ^2.4.0
  canine_sync:
    path: package/canine_sync
  flow_builder: ^0.0.10
  form_inputs:
    path: package/form_inputs
  formz: ^0.7.0
  flutter_secure_storage: ^9.0.0
  logging: ^1.2.0
  flutter_svg: ^2.0.10+1
  easy_refresh: ^3.3.4
  flutter_spinkit: ^5.2.0
  uuid: ^4.3.3
  file_selector: ^1.0.3
  rxdart: ^0.27.7
  go_router: ^13.2.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  custom_lint: ^0.6.2
  test: ^1.24.9
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/