name: applib
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.4
  easy_refresh: ^3.4.0
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  formz: ^0.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  logging: ^1.2.0
  path: ^1.9.0
  rxdart: ^0.27.7
  canine_sync:
    path: ../../packages/canine_sync
  form_inputs:
    path: ../../packages/form_inputs
  go_router: ^14.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
