//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Conversation struct {
	ID            int64 `sql:"primary_key"`
	User1ID       int64
	User2ID       int64
	CreatedAt     time.Time
	LastMessageID int64
}
