//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Messages struct {
	ID             int64 `sql:"primary_key"`
	ConversationID int64
	SenderID       int64
	Message        string
	CreatedAt      time.Time
}
