//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type MessageType string

const (
	MessageType_Ask MessageType = "ask"
	MessageType_Msg MessageType = "msg"
)

func (e *MessageType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "ask":
		*e = MessageType_Ask
	case "msg":
		*e = MessageType_Msg
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for MessageType enum")
	}

	return nil
}

func (e MessageType) String() string {
	return string(e)
}
