//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var UserType = &struct {
	External postgres.StringExpression
	Internal postgres.StringExpression
	Bot      postgres.StringExpression
}{
	External: postgres.NewEnumValue("external"),
	Internal: postgres.NewEnumValue("internal"),
	Bot:      postgres.NewEnumValue("bot"),
}
